package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.ArrayList;
import java.util.Hashtable;

public class NTCAnalyticsEngineControl extends NTCConfigurationEntity implements KvmSerializable
{

    
    public String EngineToken;
    
    public String EngineConfigToken;
    
    public ArrayList< String> InputToken =new ArrayList<String >();
    
    public ArrayList< String> ReceiverToken =new ArrayList<String >();
    
    public NTCMulticastConfiguration Multicast;
    
    public NTCConfig Subscription;
    
    public NTCEnums.ModeOfOperation Mode=NTCEnums.ModeOfOperation.Idle;

    public NTCAnalyticsEngineControl ()
    {
    }

    public NTCAnalyticsEngineControl (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("EngineToken"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.EngineToken = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.EngineToken = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("EngineConfigToken"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.EngineConfigToken = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.EngineConfigToken = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("InputToken"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.InputToken==null)
                        {
                            this.InputToken = new ArrayList< String>();
                        }
                        Object j =obj;
                        String j1= j.toString();
                        this.InputToken.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("ReceiverToken"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.ReceiverToken==null)
                        {
                            this.ReceiverToken = new ArrayList< String>();
                        }
                        Object j =obj;
                        String j1= j.toString();
                        this.ReceiverToken.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("Multicast"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Multicast = (NTCMulticastConfiguration)__envelope.get(j,NTCMulticastConfiguration.class,false);
                    }
                    continue;
                }
                if (info.name.equals("Subscription"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Subscription = (NTCConfig)__envelope.get(j,NTCConfig.class,false);
                    }
                    continue;
                }
                if (info.name.equals("Mode"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Mode = NTCEnums.ModeOfOperation.fromString(j.toString());
                            }
                        }
                        else if (obj instanceof NTCEnums.ModeOfOperation){
                            this.Mode = (NTCEnums.ModeOfOperation)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return EngineToken;
        }
        if(propertyIndex==count+1)
        {
            return EngineConfigToken;
        }
        if(propertyIndex>=count+2 && propertyIndex < count+2+this.InputToken.size())
        {
            return this.InputToken.get(propertyIndex-(count+2));
        }
        if(propertyIndex>=count+2+this.InputToken.size() && propertyIndex < count+2+this.InputToken.size()+this.ReceiverToken.size())
        {
            return this.ReceiverToken.get(propertyIndex-(count+2+this.InputToken.size()));
        }
        if(propertyIndex==count+2+this.InputToken.size()+this.ReceiverToken.size())
        {
            return this.Multicast!=null?this.Multicast:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3+this.InputToken.size()+this.ReceiverToken.size())
        {
            return Subscription;
        }
        if(propertyIndex==count+4+this.InputToken.size()+this.ReceiverToken.size())
        {
            return this.Mode!=null?this.Mode.toString():SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+5+InputToken.size()+ReceiverToken.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EngineToken";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EngineConfigToken";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=count+2 && propertyIndex < count+2+this.InputToken.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InputToken";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=count+2+this.InputToken.size() && propertyIndex < count+2+this.InputToken.size()+this.ReceiverToken.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ReceiverToken";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+2+this.InputToken.size()+this.ReceiverToken.size())
        {
            info.type = NTCMulticastConfiguration.class;
            info.name = "Multicast";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+3+this.InputToken.size()+this.ReceiverToken.size())
        {
            info.type = NTCConfig.class;
            info.name = "Subscription";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==count+4+this.InputToken.size()+this.ReceiverToken.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Mode";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

