package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.ArrayList;
import java.util.Hashtable;

public class NTCAnalyticsDeviceEngineConfiguration extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< NTCEngineConfiguration> EngineConfiguration =new ArrayList<NTCEngineConfiguration >();
    
    public NTCAnalyticsDeviceEngineConfigurationExtension Extension;

    public NTCAnalyticsDeviceEngineConfiguration ()
    {
    }

    public NTCAnalyticsDeviceEngineConfiguration (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("EngineConfiguration"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.EngineConfiguration==null)
                        {
                            this.EngineConfiguration = new ArrayList< NTCEngineConfiguration>();
                        }
                        Object j =obj;
                        NTCEngineConfiguration j1= (NTCEngineConfiguration)__envelope.get(j,NTCEngineConfiguration.class,false);
                        this.EngineConfiguration.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("Extension"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Extension = (NTCAnalyticsDeviceEngineConfigurationExtension)__envelope.get(j,NTCAnalyticsDeviceEngineConfigurationExtension.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.EngineConfiguration.size())
        {
            return this.EngineConfiguration.get(propertyIndex-(0));
        }
        if(propertyIndex==0+this.EngineConfiguration.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+EngineConfiguration.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.EngineConfiguration.size())
        {
            info.type = NTCEngineConfiguration.class;
            info.name = "EngineConfiguration";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==0+this.EngineConfiguration.size())
        {
            info.type = NTCAnalyticsDeviceEngineConfigurationExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

