package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NTCCapabilities extends AttributeContainer implements KvmSerializable
{

    
    public Boolean EFlip=false;
    
    public Boolean Reverse=false;
    
    public Boolean GetCompatibleConfigurations=false;
    
    public Boolean MoveStatus=false;
    
    public Boolean StatusPosition=false;

    public NTCCapabilities ()
    {
    }

    public NTCCapabilities (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;







        if (inObj.hasAttribute("EFlip"))
        {	
            Object j = inObj.getAttribute("EFlip");
            if (j != null)
            {
                EFlip = new Boolean(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("Reverse"))
        {	
            Object j = inObj.getAttribute("Reverse");
            if (j != null)
            {
                Reverse = new Boolean(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("GetCompatibleConfigurations"))
        {	
            Object j = inObj.getAttribute("GetCompatibleConfigurations");
            if (j != null)
            {
                GetCompatibleConfigurations = new Boolean(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("MoveStatus"))
        {	
            Object j = inObj.getAttribute("MoveStatus");
            if (j != null)
            {
                MoveStatus = new Boolean(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("StatusPosition"))
        {	
            Object j = inObj.getAttribute("StatusPosition");
            if (j != null)
            {
                StatusPosition = new Boolean(j.toString());
	            
            }
        }

    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 5;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "EFlip";
            info.namespace= "";
            if(this.EFlip!=null)
            {
                info.setValue(this.EFlip);
            }
            
        }
        if(index==1)
        {
            info.name = "Reverse";
            info.namespace= "";
            if(this.Reverse!=null)
            {
                info.setValue(this.Reverse);
            }
            
        }
        if(index==2)
        {
            info.name = "GetCompatibleConfigurations";
            info.namespace= "";
            if(this.GetCompatibleConfigurations!=null)
            {
                info.setValue(this.GetCompatibleConfigurations);
            }
            
        }
        if(index==3)
        {
            info.name = "MoveStatus";
            info.namespace= "";
            if(this.MoveStatus!=null)
            {
                info.setValue(this.MoveStatus);
            }
            
        }
        if(index==4)
        {
            info.name = "StatusPosition";
            info.namespace= "";
            if(this.StatusPosition!=null)
            {
                info.setValue(this.StatusPosition);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

