package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NTCColor extends AttributeContainer implements KvmSerializable
{

    
    public Float X=0f;
    
    public Float Y=0f;
    
    public Float Z=0f;
    
    public String Colorspace;

    public NTCColor ()
    {
    }

    public NTCColor (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;







        if (inObj.hasAttribute("X"))
        {	
            Object j = inObj.getAttribute("X");
            if (j != null)
            {
                X = new Float(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("Y"))
        {	
            Object j = inObj.getAttribute("Y");
            if (j != null)
            {
                Y = new Float(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("Z"))
        {	
            Object j = inObj.getAttribute("Z");
            if (j != null)
            {
                Z = new Float(j.toString());
	            
            }
        }

        if (inObj.hasAttribute("Colorspace"))
        {	
            Object j = inObj.getAttribute("Colorspace");
            if (j != null)
            {
                Colorspace = j.toString();
	            
            }
        }

    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 4;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "X";
            info.namespace= "";
            if(this.X!=null)
            {
                info.setValue(this.X);
            }
            
        }
        if(index==1)
        {
            info.name = "Y";
            info.namespace= "";
            if(this.Y!=null)
            {
                info.setValue(this.Y);
            }
            
        }
        if(index==2)
        {
            info.name = "Z";
            info.namespace= "";
            if(this.Z!=null)
            {
                info.setValue(this.Z);
            }
            
        }
        if(index==3)
        {
            info.name = "Colorspace";
            info.namespace= "";
            if(this.Colorspace!=null)
            {
                info.setValue(this.Colorspace);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

