package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import javax.xml.namespace.QName;

public class NTCConfig extends AttributeContainer implements KvmSerializable
{

    
    public NTCItemList Parameters;
    
    public String Name;
    
    public QName Type;

    public NTCConfig ()
    {
    }

    public NTCConfig (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Parameters"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Parameters = (NTCItemList)__envelope.get(j,NTCItemList.class,false);
                    }
                    continue;
                }

            }

        }



        if (inObj.hasAttribute("Name"))
        {	
            Object j = inObj.getAttribute("Name");
            if (j != null)
            {
                Name = j.toString();
	            
            }
        }

        if (inObj.hasAttribute("Type"))
        {	
            Object j = inObj.getAttribute("Type");
            if (j != null)
            {
                Type = new QName(j.toString());
	            
            }
        }

    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Parameters;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = NTCItemList.class;
            info.name = "Parameters";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 2;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "Name";
            info.namespace= "";
            if(this.Name!=null)
            {
                info.setValue(this.Name);
            }
            
        }
        if(index==1)
        {
            info.name = "Type";
            info.namespace= "";
            if(this.Type!=null)
            {
                info.setValue(this.Type);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

