package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;

public class NTCExtendedSoapSerializationEnvelope extends SoapSerializationEnvelope {
    static HashMap< String,Class> classNames = new HashMap< String, Class>();
    static {
        classNames.put("http://docs.oasis-open.org/wsn/b-2^^FilterType",NTCFilterType.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Vector2D",NTCVector2D.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Vector1D",NTCVector1D.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZVector",NTCPTZVector.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Vector",NTCVector.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Rectangle",NTCRectangle.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Color",NTCColor.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DeviceEntity",NTCDeviceEntity.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IntRectangle",NTCIntRectangle.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FloatRange",NTCFloatRange.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DurationRange",NTCDurationRange.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSource",NTCVideoSource.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceExtension",NTCVideoSourceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceExtension2",NTCVideoSourceExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioSource",NTCAudioSource.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ConfigurationEntity",NTCConfigurationEntity.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceConfiguration",NTCVideoSourceConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceConfigurationExtension",NTCVideoSourceConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoSourceConfigurationExtension2",NTCVideoSourceConfigurationExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Rotate",NTCRotate.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RotateExtension",NTCRotateExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LensProjection",NTCLensProjection.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LensOffset",NTCLensOffset.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LensDescription",NTCLensDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SceneOrientation",NTCSceneOrientation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoEncoderConfiguration",NTCVideoEncoderConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoResolution",NTCVideoResolution.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoRateControl",NTCVideoRateControl.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Mpeg4Configuration",NTCMpeg4Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^H264Configuration",NTCH264Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoEncoder2Configuration",NTCVideoEncoder2Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoResolution2",NTCVideoResolution2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoRateControl2",NTCVideoRateControl2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioSourceConfiguration",NTCAudioSourceConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioEncoderConfiguration",NTCAudioEncoderConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioEncoder2Configuration",NTCAudioEncoder2Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoAnalyticsConfiguration",NTCVideoAnalyticsConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataConfiguration",NTCMetadataConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataConfigurationExtension",NTCMetadataConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZFilter",NTCPTZFilter.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventSubscription_SubscriptionPolicy",NTCEventSubscription_SubscriptionPolicy.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventSubscription",NTCEventSubscription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutput",NTCVideoOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutputExtension",NTCVideoOutputExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^VideoOutputConfiguration",NTCVideoOutputConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioOutput",NTCAudioOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioOutputConfiguration",NTCAudioOutputConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AudioDecoderConfiguration",NTCAudioDecoderConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MulticastConfiguration",NTCMulticastConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterface",NTCNetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceExtension",NTCNetworkInterfaceExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot3Configuration",NTCDot3Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceExtension2",NTCNetworkInterfaceExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceLink",NTCNetworkInterfaceLink.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceConnectionSetting",NTCNetworkInterfaceConnectionSetting.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NetworkInterfaceInfo",NTCNetworkInterfaceInfo.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6NetworkInterface",NTCIPv6NetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4NetworkInterface",NTCIPv4NetworkInterface.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv4Configuration",NTCIPv4Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6Configuration",NTCIPv6Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPv6ConfigurationExtension",NTCIPv6ConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IPAddress",NTCIPAddress.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PrefixedIPv4Address",NTCPrefixedIPv4Address.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PrefixedIPv6Address",NTCPrefixedIPv6Address.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11Configuration",NTCDot11Configuration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11SecurityConfiguration",NTCDot11SecurityConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11SecurityConfigurationExtension",NTCDot11SecurityConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11PSKSet",NTCDot11PSKSet.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Dot11PSKSetExtension",NTCDot11PSKSetExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RelayOutputSettings",NTCRelayOutputSettings.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RelayOutput",NTCRelayOutput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DigitalInput",NTCDigitalInput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNode",NTCPTZNode.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNodeExtension",NTCPTZNodeExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZNodeExtension2",NTCPTZNodeExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZPresetTourSupported",NTCPTZPresetTourSupported.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZPresetTourSupportedExtension",NTCPTZPresetTourSupportedExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfiguration",NTCPTZConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfigurationExtension",NTCPTZConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfigurationExtension2",NTCPTZConfigurationExtension2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTControlDirection",NTCPTControlDirection.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTControlDirectionExtension",NTCPTControlDirectionExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EFlip",NTCEFlip.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Reverse",NTCReverse.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfigurationOptions",NTCPTZConfigurationOptions.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZConfigurationOptions2",NTCPTZConfigurationOptions2.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTControlDirectionOptions",NTCPTControlDirectionOptions.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTControlDirectionOptionsExtension",NTCPTControlDirectionOptionsExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EFlipOptions",NTCEFlipOptions.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EFlipOptionsExtension",NTCEFlipOptionsExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ReverseOptions",NTCReverseOptions.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ReverseOptionsExtension",NTCReverseOptionsExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PanTiltLimits",NTCPanTiltLimits.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ZoomLimits",NTCZoomLimits.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpaces",NTCPTZSpaces.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpacesExtension",NTCPTZSpacesExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Space2DDescription",NTCSpace2DDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Space1DDescription",NTCSpace1DDescription.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZSpeed",NTCPTZSpeed.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PTZPreset",NTCPTZPreset.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration",NTCFocusConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettings",NTCImagingSettings.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension",NTCImagingSettingsExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Exposure",NTCExposure.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WideDynamicRange",NTCWideDynamicRange.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BacklightCompensation",NTCBacklightCompensation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance",NTCWhiteBalance.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettings20",NTCImagingSettings20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension20",NTCImagingSettingsExtension20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension202",NTCImagingSettingsExtension202.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension203",NTCImagingSettingsExtension203.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImagingSettingsExtension204",NTCImagingSettingsExtension204.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImageStabilization",NTCImageStabilization.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ImageStabilizationExtension",NTCImageStabilizationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IrCutFilterAutoAdjustment",NTCIrCutFilterAutoAdjustment.class);
        classNames.put("http://www.onvif.org/ver10/schema^^IrCutFilterAutoAdjustmentExtension",NTCIrCutFilterAutoAdjustmentExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WideDynamicRange20",NTCWideDynamicRange20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^BacklightCompensation20",NTCBacklightCompensation20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Exposure20",NTCExposure20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ToneCompensation",NTCToneCompensation.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ToneCompensationExtension",NTCToneCompensationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Defogging",NTCDefogging.class);
        classNames.put("http://www.onvif.org/ver10/schema^^DefoggingExtension",NTCDefoggingExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^NoiseReduction",NTCNoiseReduction.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance20",NTCWhiteBalance20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^WhiteBalance20Extension",NTCWhiteBalance20Extension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration20",NTCFocusConfiguration20.class);
        classNames.put("http://www.onvif.org/ver10/schema^^FocusConfiguration20Extension",NTCFocusConfiguration20Extension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemList_SimpleItem",NTCItemList_SimpleItem.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemList_ElementItem",NTCItemList_ElementItem.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemList",NTCItemList.class);
        classNames.put("http://www.onvif.org/ver10/schema^^ItemListExtension",NTCItemListExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineConfiguration",NTCAnalyticsEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineConfigurationExtension",NTCAnalyticsEngineConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RuleEngineConfiguration",NTCRuleEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^RuleEngineConfigurationExtension",NTCRuleEngineConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Config",NTCConfig.class);
        classNames.put("http://www.onvif.org/ver10/schema^^PaneLayout",NTCPaneLayout.class);
        classNames.put("http://www.onvif.org/ver10/schema^^Layout",NTCLayout.class);
        classNames.put("http://www.onvif.org/ver10/schema^^LayoutExtension",NTCLayoutExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EventFilter",NTCEventFilter.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngine",NTCAnalyticsEngine.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceEngineConfiguration",NTCAnalyticsDeviceEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsDeviceEngineConfigurationExtension",NTCAnalyticsDeviceEngineConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^EngineConfiguration",NTCEngineConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineInputInfo",NTCAnalyticsEngineInputInfo.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineInputInfoExtension",NTCAnalyticsEngineInputInfoExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineInput",NTCAnalyticsEngineInput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SourceIdentification",NTCSourceIdentification.class);
        classNames.put("http://www.onvif.org/ver10/schema^^SourceIdentificationExtension",NTCSourceIdentificationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataInput",NTCMetadataInput.class);
        classNames.put("http://www.onvif.org/ver10/schema^^MetadataInputExtension",NTCMetadataInputExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^AnalyticsEngineControl",NTCAnalyticsEngineControl.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDPosConfiguration",NTCOSDPosConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDPosConfigurationExtension",NTCOSDPosConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDColor",NTCOSDColor.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDTextConfiguration",NTCOSDTextConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDTextConfigurationExtension",NTCOSDTextConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDImgConfiguration",NTCOSDImgConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDImgConfigurationExtension",NTCOSDImgConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDConfiguration",NTCOSDConfiguration.class);
        classNames.put("http://www.onvif.org/ver10/schema^^OSDConfigurationExtension",NTCOSDConfigurationExtension.class);
        classNames.put("http://www.onvif.org/ver20/ptz/wsdl^^Capabilities",NTCCapabilities.class);
        classNames.put("http://www.onvif.org/ver20/ptz/wsdl^^GetNodesResponse",NTCGetNodesResponse.class);
        classNames.put("http://www.onvif.org/ver20/ptz/wsdl^^GetConfigurationsResponse",NTCGetConfigurationsResponse.class);
        classNames.put("http://www.onvif.org/ver20/ptz/wsdl^^GetPresetsResponse",NTCGetPresetsResponse.class);
    }   

    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public NTCExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public NTCExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new NTCMarshalGuid().register(this);
        new MarshalFloat().register(this);
    }

    

    @Override
    protected void writeProperty(XmlSerializer writer, Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {

            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=String.class  )) {
                String xmlName=NTCHelper.getKeyByValue(classNames,obj.getClass());
                if(xmlName!=null) {
                    String[] parts = xmlName.split("\\^\\^");
                    String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        String xsdPrefix = writer.getPrefix(xsd, true);
                        String myType = (String) type.type;
                        String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }
    public SoapObject GetExceptionDetail(Element detailElement,String exceptionElementNS,String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public Object GetHeader(Element detailElement) {
        if(detailElement.getChildCount()>0 && detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    
    public Object get(Object soap,Class cl,boolean typeFromClass)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(soap instanceof Vector || typeFromClass)
            {
                Constructor ctor = cl.getConstructor(Object.class,NTCExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
            {
                if(soap instanceof SoapObject)
                {
                    if(cl ==SoapObject.class)
                    {
                        return soap;
                    }
                    String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                Constructor ctor = cl.getConstructor(Object.class,NTCExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }

} 

