package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------



import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class NTCGetConfigurationsResponse extends Vector< NTCPTZConfiguration> implements KvmSerializable
{
    
    public NTCGetConfigurationsResponse(){}
    
    public NTCGetConfigurationsResponse(Object inObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                NTCPTZConfiguration j1= (NTCPTZConfiguration)__envelope.get(j,NTCPTZConfiguration.class,false);
                add(j1);
            }
        }
}
    
    @Override
    public Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "PTZConfiguration";
        info.type = NTCPTZConfiguration.class;
    	info.namespace= "http://www.onvif.org/ver20/ptz/wsdl";
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }

    
}