package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class NTCIPv4Configuration extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< NTCPrefixedIPv4Address> Manual =new ArrayList<NTCPrefixedIPv4Address >();
    
    public NTCPrefixedIPv4Address LinkLocal;
    
    public NTCPrefixedIPv4Address FromDHCP;
    
    public Boolean DHCP=false;

    public NTCIPv4Configuration ()
    {
    }

    public NTCIPv4Configuration (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Manual"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.Manual==null)
                        {
                            this.Manual = new ArrayList< NTCPrefixedIPv4Address>();
                        }
                        Object j =obj;
                        NTCPrefixedIPv4Address j1= (NTCPrefixedIPv4Address)__envelope.get(j,NTCPrefixedIPv4Address.class,false);
                        this.Manual.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("LinkLocal"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.LinkLocal = (NTCPrefixedIPv4Address)__envelope.get(j,NTCPrefixedIPv4Address.class,false);
                    }
                    continue;
                }
                if (info.name.equals("FromDHCP"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.FromDHCP = (NTCPrefixedIPv4Address)__envelope.get(j,NTCPrefixedIPv4Address.class,false);
                    }
                    continue;
                }
                if (info.name.equals("DHCP"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.DHCP = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.DHCP = (Boolean)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.Manual.size())
        {
            return this.Manual.get(propertyIndex-(0));
        }
        if(propertyIndex==0+this.Manual.size())
        {
            return this.LinkLocal!=null?this.LinkLocal:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1+this.Manual.size())
        {
            return this.FromDHCP!=null?this.FromDHCP:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2+this.Manual.size())
        {
            return DHCP;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3+Manual.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.Manual.size())
        {
            info.type = NTCPrefixedIPv4Address.class;
            info.name = "Manual";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==0+this.Manual.size())
        {
            info.type = NTCPrefixedIPv4Address.class;
            info.name = "LinkLocal";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1+this.Manual.size())
        {
            info.type = NTCPrefixedIPv4Address.class;
            info.name = "FromDHCP";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2+this.Manual.size())
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DHCP";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

