package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NTCImagingSettingsExtension203 extends AttributeContainer implements KvmSerializable
{

    
    public NTCToneCompensation ToneCompensation;
    
    public NTCDefogging Defogging;
    
    public NTCNoiseReduction NoiseReduction;
    
    public NTCImagingSettingsExtension204 Extension;

    public NTCImagingSettingsExtension203 ()
    {
    }

    public NTCImagingSettingsExtension203 (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("ToneCompensation"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.ToneCompensation = (NTCToneCompensation)__envelope.get(j,NTCToneCompensation.class,false);
                    }
                    continue;
                }
                if (info.name.equals("Defogging"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Defogging = (NTCDefogging)__envelope.get(j,NTCDefogging.class,false);
                    }
                    continue;
                }
                if (info.name.equals("NoiseReduction"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.NoiseReduction = (NTCNoiseReduction)__envelope.get(j,NTCNoiseReduction.class,false);
                    }
                    continue;
                }
                if (info.name.equals("Extension"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Extension = (NTCImagingSettingsExtension204)__envelope.get(j,NTCImagingSettingsExtension204.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ToneCompensation!=null?this.ToneCompensation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Defogging!=null?this.Defogging:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.NoiseReduction!=null?this.NoiseReduction:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = NTCToneCompensation.class;
            info.name = "ToneCompensation";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = NTCDefogging.class;
            info.name = "Defogging";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = NTCNoiseReduction.class;
            info.name = "NoiseReduction";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==3)
        {
            info.type = NTCImagingSettingsExtension204.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

