package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class NTCNetworkInterfaceLink extends AttributeContainer implements KvmSerializable
{

    
    public NTCNetworkInterfaceConnectionSetting AdminSettings;
    
    public NTCNetworkInterfaceConnectionSetting OperSettings;
    
    public Integer InterfaceType=0;

    public NTCNetworkInterfaceLink ()
    {
    }

    public NTCNetworkInterfaceLink (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("AdminSettings"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.AdminSettings = (NTCNetworkInterfaceConnectionSetting)__envelope.get(j,NTCNetworkInterfaceConnectionSetting.class,false);
                    }
                    continue;
                }
                if (info.name.equals("OperSettings"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.OperSettings = (NTCNetworkInterfaceConnectionSetting)__envelope.get(j,NTCNetworkInterfaceConnectionSetting.class,false);
                    }
                    continue;
                }
                if (info.name.equals("InterfaceType"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.InterfaceType = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.InterfaceType = (Integer)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return AdminSettings;
        }
        if(propertyIndex==1)
        {
            return OperSettings;
        }
        if(propertyIndex==2)
        {
            return InterfaceType;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = NTCNetworkInterfaceConnectionSetting.class;
            info.name = "AdminSettings";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1)
        {
            info.type = NTCNetworkInterfaceConnectionSetting.class;
            info.name = "OperSettings";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "InterfaceType";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

