package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class NTCNetworkInterfaceExtension extends AttributeContainer implements KvmSerializable
{

    
    public Integer InterfaceType=0;
    
    public ArrayList< NTCDot3Configuration> Dot3 =new ArrayList<NTCDot3Configuration >();
    
    public ArrayList< NTCDot11Configuration> Dot11 =new ArrayList<NTCDot11Configuration >();
    
    public NTCNetworkInterfaceExtension2 Extension;

    public NTCNetworkInterfaceExtension ()
    {
    }

    public NTCNetworkInterfaceExtension (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("InterfaceType"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.InterfaceType = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.InterfaceType = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Dot3"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.Dot3==null)
                        {
                            this.Dot3 = new ArrayList< NTCDot3Configuration>();
                        }
                        Object j =obj;
                        NTCDot3Configuration j1= (NTCDot3Configuration)__envelope.get(j,NTCDot3Configuration.class,false);
                        this.Dot3.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("Dot11"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.Dot11==null)
                        {
                            this.Dot11 = new ArrayList< NTCDot11Configuration>();
                        }
                        Object j =obj;
                        NTCDot11Configuration j1= (NTCDot11Configuration)__envelope.get(j,NTCDot11Configuration.class,false);
                        this.Dot11.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("Extension"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Extension = (NTCNetworkInterfaceExtension2)__envelope.get(j,NTCNetworkInterfaceExtension2.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return InterfaceType;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.Dot3.size())
        {
            return this.Dot3.get(propertyIndex-(1));
        }
        if(propertyIndex>=1+this.Dot3.size() && propertyIndex < 1+this.Dot3.size()+this.Dot11.size())
        {
            return this.Dot11.get(propertyIndex-(1+this.Dot3.size()));
        }
        if(propertyIndex==1+this.Dot3.size()+this.Dot11.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+Dot3.size()+Dot11.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "InterfaceType";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.Dot3.size())
        {
            info.type = NTCDot3Configuration.class;
            info.name = "Dot3";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=1+this.Dot3.size() && propertyIndex < 1+this.Dot3.size()+this.Dot11.size())
        {
            info.type = NTCDot11Configuration.class;
            info.name = "Dot11";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1+this.Dot3.size()+this.Dot11.size())
        {
            info.type = NTCNetworkInterfaceExtension2.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

