package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

public class NTCOSDReference  
{

    
    public String value;

    public NTCOSDReference ()
    {
    }

    public NTCOSDReference (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;

        if(!(inObj instanceof SoapObject))
        {
            Object j =(Object)inObj;
            value = j.toString();
        }

    }
    public Object getSimpleValue()
    {
        Object value=this.value != null ? this.value.toString() : "";
        SoapPrimitive primitive = new SoapPrimitive("http://www.onvif.org/ver10/schema", "value",value);
        
        return primitive;
    }    
}

