package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class NTCPTZSpaces extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< NTCSpace2DDescription> AbsolutePanTiltPositionSpace =new ArrayList<NTCSpace2DDescription >();
    
    public ArrayList< NTCSpace1DDescription> AbsoluteZoomPositionSpace =new ArrayList<NTCSpace1DDescription >();
    
    public ArrayList< NTCSpace2DDescription> RelativePanTiltTranslationSpace =new ArrayList<NTCSpace2DDescription >();
    
    public ArrayList< NTCSpace1DDescription> RelativeZoomTranslationSpace =new ArrayList<NTCSpace1DDescription >();
    
    public ArrayList< NTCSpace2DDescription> ContinuousPanTiltVelocitySpace =new ArrayList<NTCSpace2DDescription >();
    
    public ArrayList< NTCSpace1DDescription> ContinuousZoomVelocitySpace =new ArrayList<NTCSpace1DDescription >();
    
    public ArrayList< NTCSpace1DDescription> PanTiltSpeedSpace =new ArrayList<NTCSpace1DDescription >();
    
    public ArrayList< NTCSpace1DDescription> ZoomSpeedSpace =new ArrayList<NTCSpace1DDescription >();
    
    public NTCPTZSpacesExtension Extension;

    public NTCPTZSpaces ()
    {
    }

    public NTCPTZSpaces (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("AbsolutePanTiltPositionSpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.AbsolutePanTiltPositionSpace==null)
                        {
                            this.AbsolutePanTiltPositionSpace = new ArrayList< NTCSpace2DDescription>();
                        }
                        Object j =obj;
                        NTCSpace2DDescription j1= (NTCSpace2DDescription)__envelope.get(j,NTCSpace2DDescription.class,false);
                        this.AbsolutePanTiltPositionSpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("AbsoluteZoomPositionSpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.AbsoluteZoomPositionSpace==null)
                        {
                            this.AbsoluteZoomPositionSpace = new ArrayList< NTCSpace1DDescription>();
                        }
                        Object j =obj;
                        NTCSpace1DDescription j1= (NTCSpace1DDescription)__envelope.get(j,NTCSpace1DDescription.class,false);
                        this.AbsoluteZoomPositionSpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("RelativePanTiltTranslationSpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.RelativePanTiltTranslationSpace==null)
                        {
                            this.RelativePanTiltTranslationSpace = new ArrayList< NTCSpace2DDescription>();
                        }
                        Object j =obj;
                        NTCSpace2DDescription j1= (NTCSpace2DDescription)__envelope.get(j,NTCSpace2DDescription.class,false);
                        this.RelativePanTiltTranslationSpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("RelativeZoomTranslationSpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.RelativeZoomTranslationSpace==null)
                        {
                            this.RelativeZoomTranslationSpace = new ArrayList< NTCSpace1DDescription>();
                        }
                        Object j =obj;
                        NTCSpace1DDescription j1= (NTCSpace1DDescription)__envelope.get(j,NTCSpace1DDescription.class,false);
                        this.RelativeZoomTranslationSpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("ContinuousPanTiltVelocitySpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.ContinuousPanTiltVelocitySpace==null)
                        {
                            this.ContinuousPanTiltVelocitySpace = new ArrayList< NTCSpace2DDescription>();
                        }
                        Object j =obj;
                        NTCSpace2DDescription j1= (NTCSpace2DDescription)__envelope.get(j,NTCSpace2DDescription.class,false);
                        this.ContinuousPanTiltVelocitySpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("ContinuousZoomVelocitySpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.ContinuousZoomVelocitySpace==null)
                        {
                            this.ContinuousZoomVelocitySpace = new ArrayList< NTCSpace1DDescription>();
                        }
                        Object j =obj;
                        NTCSpace1DDescription j1= (NTCSpace1DDescription)__envelope.get(j,NTCSpace1DDescription.class,false);
                        this.ContinuousZoomVelocitySpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("PanTiltSpeedSpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.PanTiltSpeedSpace==null)
                        {
                            this.PanTiltSpeedSpace = new ArrayList< NTCSpace1DDescription>();
                        }
                        Object j =obj;
                        NTCSpace1DDescription j1= (NTCSpace1DDescription)__envelope.get(j,NTCSpace1DDescription.class,false);
                        this.PanTiltSpeedSpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("ZoomSpeedSpace"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.ZoomSpeedSpace==null)
                        {
                            this.ZoomSpeedSpace = new ArrayList< NTCSpace1DDescription>();
                        }
                        Object j =obj;
                        NTCSpace1DDescription j1= (NTCSpace1DDescription)__envelope.get(j,NTCSpace1DDescription.class,false);
                        this.ZoomSpeedSpace.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("Extension"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Extension = (NTCPTZSpacesExtension)__envelope.get(j,NTCPTZSpacesExtension.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size())
        {
            return this.AbsolutePanTiltPositionSpace.get(propertyIndex-(0));
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size())
        {
            return this.AbsoluteZoomPositionSpace.get(propertyIndex-(0+this.AbsolutePanTiltPositionSpace.size()));
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size())
        {
            return this.RelativePanTiltTranslationSpace.get(propertyIndex-(0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()));
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size())
        {
            return this.RelativeZoomTranslationSpace.get(propertyIndex-(0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()));
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size())
        {
            return this.ContinuousPanTiltVelocitySpace.get(propertyIndex-(0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()));
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size())
        {
            return this.ContinuousZoomVelocitySpace.get(propertyIndex-(0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()));
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size())
        {
            return this.PanTiltSpeedSpace.get(propertyIndex-(0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()));
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size()+this.ZoomSpeedSpace.size())
        {
            return this.ZoomSpeedSpace.get(propertyIndex-(0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size()));
        }
        if(propertyIndex==0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size()+this.ZoomSpeedSpace.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+AbsolutePanTiltPositionSpace.size()+AbsoluteZoomPositionSpace.size()+RelativePanTiltTranslationSpace.size()+RelativeZoomTranslationSpace.size()+ContinuousPanTiltVelocitySpace.size()+ContinuousZoomVelocitySpace.size()+PanTiltSpeedSpace.size()+ZoomSpeedSpace.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size())
        {
            info.type = NTCSpace2DDescription.class;
            info.name = "AbsolutePanTiltPositionSpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size())
        {
            info.type = NTCSpace1DDescription.class;
            info.name = "AbsoluteZoomPositionSpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size())
        {
            info.type = NTCSpace2DDescription.class;
            info.name = "RelativePanTiltTranslationSpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size())
        {
            info.type = NTCSpace1DDescription.class;
            info.name = "RelativeZoomTranslationSpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size())
        {
            info.type = NTCSpace2DDescription.class;
            info.name = "ContinuousPanTiltVelocitySpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size())
        {
            info.type = NTCSpace1DDescription.class;
            info.name = "ContinuousZoomVelocitySpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size())
        {
            info.type = NTCSpace1DDescription.class;
            info.name = "PanTiltSpeedSpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size() && propertyIndex < 0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size()+this.ZoomSpeedSpace.size())
        {
            info.type = NTCSpace1DDescription.class;
            info.name = "ZoomSpeedSpace";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==0+this.AbsolutePanTiltPositionSpace.size()+this.AbsoluteZoomPositionSpace.size()+this.RelativePanTiltTranslationSpace.size()+this.RelativeZoomTranslationSpace.size()+this.ContinuousPanTiltVelocitySpace.size()+this.ContinuousZoomVelocitySpace.size()+this.PanTiltSpeedSpace.size()+this.ZoomSpeedSpace.size())
        {
            info.type = NTCPTZSpacesExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

