package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class NTCPTZPresetTourSupported extends AttributeContainer implements KvmSerializable
{

    
    public Integer MaximumNumberOfPresetTours=0;
    
    public ArrayList< NTCEnums.PTZPresetTourOperation> PTZPresetTourOperation =new ArrayList<NTCEnums.PTZPresetTourOperation >();
    
    public NTCPTZPresetTourSupportedExtension Extension;

    public NTCPTZPresetTourSupported ()
    {
    }

    public NTCPTZPresetTourSupported (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("MaximumNumberOfPresetTours"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.MaximumNumberOfPresetTours = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.MaximumNumberOfPresetTours = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("PTZPresetTourOperation"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.PTZPresetTourOperation==null)
                        {
                            this.PTZPresetTourOperation = new ArrayList< NTCEnums.PTZPresetTourOperation>();
                        }
                        Object j =obj;
                        NTCEnums.PTZPresetTourOperation j1= NTCEnums.PTZPresetTourOperation.fromString(j.toString());
                        this.PTZPresetTourOperation.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("Extension"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Extension = (NTCPTZPresetTourSupportedExtension)__envelope.get(j,NTCPTZPresetTourSupportedExtension.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return MaximumNumberOfPresetTours;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.PTZPresetTourOperation.size())
        {
            return this.PTZPresetTourOperation.get(propertyIndex-(1));
        }
        if(propertyIndex==1+this.PTZPresetTourOperation.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+PTZPresetTourOperation.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "MaximumNumberOfPresetTours";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.PTZPresetTourOperation.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PTZPresetTourOperation";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1+this.PTZPresetTourOperation.size())
        {
            info.type = NTCPTZPresetTourSupportedExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

