package com.hhbgk.webservice.discovery.more;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------




import android.util.Log;

import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;
import org.ksoap2.transport.Transport;

import java.util.List;


public class NTCPTZBinding
{
    interface NTCIWcfMethod
    {
        NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url="http://levan1994.ddns.net:5000/onvif/media_service";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    public NTCPTZBinding(){}

    public NTCPTZBinding(String url)
    {
        this.url = url;
    }

    public NTCPTZBinding(String url,int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }

    protected Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected NTCExtendedSoapSerializationEnvelope createEnvelope()
    {
        NTCExtendedSoapSerializationEnvelope envelope= new NTCExtendedSoapSerializationEnvelope(NTCExtendedSoapSerializationEnvelope.VER12);
        return envelope;
    }
    
    protected List sendRequest(String methodName,NTCExtendedSoapSerializationEnvelope envelope,Transport transport  )throws Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    Object getResult(Class destObj,Object source,String resultName,NTCExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }

       return null;
    }

        
    public NTCCapabilities GetServiceCapabilities( ) throws Exception
    {
        return (NTCCapabilities)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GetServiceCapabilities");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (NTCCapabilities)getResult(NTCCapabilities.class,__result,"Capabilities",__envelope);
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GetServiceCapabilities");
    }
    
    public NTCGetNodesResponse GetNodes( ) throws Exception
    {
        return (NTCGetNodesResponse)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GetNodes");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (NTCGetNodesResponse)getResult(NTCGetNodesResponse.class,__result,"GetNodesResponse",__envelope);
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GetNodes");
    }
    
    public NTCPTZNode GetNode(final String NodeToken ) throws Exception
    {
        return (NTCPTZNode)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GetNode");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="NodeToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(NodeToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (NTCPTZNode)getResult(NTCPTZNode.class,__result,"PTZNode",__envelope);
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GetNode");
    }
    
    public NTCPTZConfiguration GetConfiguration(final String PTZConfigurationToken ) throws Exception
    {
        return (NTCPTZConfiguration)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GetConfiguration");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="PTZConfigurationToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(PTZConfigurationToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (NTCPTZConfiguration)getResult(NTCPTZConfiguration.class,__result,"PTZConfiguration",__envelope);
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GetConfiguration");
    }
    
    public NTCGetConfigurationsResponse GetConfigurations( ) throws Exception
    {
        return (NTCGetConfigurationsResponse)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GetConfigurations");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (NTCGetConfigurationsResponse)getResult(NTCGetConfigurationsResponse.class,__result,"GetConfigurationsResponse",__envelope);
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GetConfigurations");
    }
    
    public void SetConfiguration(final NTCPTZConfiguration PTZConfiguration,final Boolean ForcePersistence ) throws Exception
    {
        execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.onvif.org/ver20/ptz/wsdl","PTZConfiguration",new NTCPTZConfiguration().getClass());
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "SetConfiguration");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="PTZConfiguration";
                __info.type=NTCPTZConfiguration.class;
                __info.setValue(PTZConfiguration);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ForcePersistence";
                __info.type=PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(ForcePersistence);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/SetConfiguration");
    }
    
    public NTCPTZConfigurationOptions GetConfigurationOptions(final String ConfigurationToken ) throws Exception
    {
        return (NTCPTZConfigurationOptions)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GetConfigurationOptions");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ConfigurationToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ConfigurationToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (NTCPTZConfigurationOptions)getResult(NTCPTZConfigurationOptions.class,__result,"PTZConfigurationOptions",__envelope);
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GetConfigurationOptions");
    }
    
    public String SendAuxiliaryCommand(final String ProfileToken,final String AuxiliaryData ) throws Exception
    {
        return (String)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "SendAuxiliaryCommand");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ProfileToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ProfileToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="AuxiliaryData";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(AuxiliaryData);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("AuxiliaryResponse");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/SendAuxiliaryCommand");
    }
    
    public NTCGetPresetsResponse GetPresets(final String ProfileToken ) throws Exception
    {
        return (NTCGetPresetsResponse)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GetPresets");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ProfileToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ProfileToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (NTCGetPresetsResponse)getResult(NTCGetPresetsResponse.class,__result,"GetPresetsResponse",__envelope);
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GetPresets");
    }
    
    public String SetPreset(final String ProfileToken,final String PresetName,final String PresetToken ) throws Exception
    {
        return (String)execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "SetPreset");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ProfileToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ProfileToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="PresetName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(PresetName!=null?PresetName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="PresetToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(PresetToken!=null?PresetToken:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                Log.e("okdone", String.valueOf(__envelope));
                Log.e("okdone", String.valueOf(__soapReq));
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("PresetToken");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    Log.e("okdone", String.valueOf(j));
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    Log.e("okdone", String.valueOf(obj));
                    return (String)obj;
                }
                return null;
            }

        },"http://www.onvif.org/ver20/ptz/wsdl/SetPreset");

    }
    
    public void RemovePreset(final String ProfileToken,final String PresetToken ) throws Exception
    {
        execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "RemovePreset");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ProfileToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ProfileToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="PresetToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(PresetToken);
                __soapReq.addProperty(__info);

                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/RemovePreset");
    }
    
    public void GotoPreset(final String ProfileToken,final String PresetToken,final NTCPTZSpeed Speed ) throws Exception
    {
        execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.onvif.org/ver20/ptz/wsdl","Speed",new NTCPTZSpeed().getClass());
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GotoPreset");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ProfileToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ProfileToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="PresetToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(PresetToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="Speed";
                __info.type=NTCPTZSpeed.class;
                __info.setValue(Speed!=null?Speed:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                Log.e("okdone", String.valueOf(__envelope));
                Log.e("okdone", String.valueOf(__soapReq));
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GotoPreset");
    }
    
    public void GotoHomePosition(final String ProfileToken,final NTCPTZSpeed Speed ) throws Exception
    {
        execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://www.onvif.org/ver20/ptz/wsdl","Speed",new NTCPTZSpeed().getClass());
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "GotoHomePosition");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ProfileToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ProfileToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="Speed";
                __info.type=NTCPTZSpeed.class;
                __info.setValue(Speed!=null?Speed:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/GotoHomePosition");
    }
    
    public void SetHomePosition(final String ProfileToken ) throws Exception
    {
        execute(new NTCIWcfMethod()
        {
            @Override
            public NTCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              NTCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://www.onvif.org/ver20/ptz/wsdl", "SetHomePosition");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://www.onvif.org/ver20/ptz/wsdl";
                __info.name="ProfileToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ProfileToken);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(NTCExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return null;
            }
        },"http://www.onvif.org/ver20/ptz/wsdl/SetHomePosition");
    }
    
    public void ContinuousMove(final String ProfileToken,final String Velocity,final String Timeout ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void RelativeMove(final String ProfileToken,final String Translation,final String Speed ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public String GetStatus(final String ProfileToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public void AbsoluteMove(final String ProfileToken,final String Position,final String Speed ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void Stop(final String ProfileToken,final String PanTilt,final String Zoom ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public String GetPresetTours(final String ProfileToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public String GetPresetTour(final String ProfileToken,final String PresetTourToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public String GetPresetTourOptions(final String ProfileToken,final String PresetTourToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public String CreatePresetTour(final String ProfileToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public void ModifyPresetTour(final String ProfileToken,final String PresetTour ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void OperatePresetTour(final String ProfileToken,final String PresetTourToken,final String Operation ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public void RemovePresetTour(final String ProfileToken,final String PresetTourToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public String GetCompatibleConfigurations(final String ProfileToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }

    
    protected Object execute(NTCIWcfMethod wcfMethod,String methodName) throws Exception
    {
        Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        NTCExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
        
    Exception convertToException(org.ksoap2.SoapFault fault,NTCExtendedSoapSerializationEnvelope envelope)
    {

        return new Exception(fault.faultstring);
    }
}


