package com.hhbgk.webservice.discovery.more;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.0
//
// Created by Quasar Development at 04/04/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class NTCSourceIdentification extends AttributeContainer implements KvmSerializable
{

    
    public String Name;
    
    public ArrayList< String> Token =new ArrayList<String >();
    
    public NTCSourceIdentificationExtension Extension;

    public NTCSourceIdentification ()
    {
    }

    public NTCSourceIdentification (Object paramObj,NTCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Name"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Name = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Name = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Token"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.Token==null)
                        {
                            this.Token = new ArrayList< String>();
                        }
                        Object j =obj;
                        String j1= j.toString();
                        this.Token.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("Extension"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Extension = (NTCSourceIdentificationExtension)__envelope.get(j,NTCSourceIdentificationExtension.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Name;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.Token.size())
        {
            return this.Token.get(propertyIndex-(1));
        }
        if(propertyIndex==1+this.Token.size())
        {
            return this.Extension!=null?this.Extension:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+Token.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Name";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.Token.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Token";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
        if(propertyIndex==1+this.Token.size())
        {
            info.type = NTCSourceIdentificationExtension.class;
            info.name = "Extension";
            info.namespace= "http://www.onvif.org/ver10/schema";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

